feat(sh): helmctl kubectx support (#34)
* feat(sh): helmctl simplified

* feat(sh): helmctl kubectx support

* feat(sh): check helm release before diff

* docs(sh): helmclt install guide

* feat(sh): helm version validation in helmctl

* fix(lgtm): helmctl install command change

* fix(devtron): helmctl install command change

diff --git a/scripts/helmctl b/scripts/helmctl
--- a/scripts/helmctl
+++ b/scripts/helmctl
@@ -1,14 +1,32 @@
 #!/bin/bash
 
+set -e
 declare -a HELM_ARGS
 
 usage() {
-    echo "Usage: $0 [install|diff|update|uninstall] -c|--config <path to YAML config file>"
+    echo "Usage: $0 [deploy|diff|uninstall] -c|--config <path to YAML config file>"
     exit 1
 }
 
 prep_req () {
     local tool_conf=".helmctl.conf"
+
+    # Check if 'helm' is installed
+    if ! command -v helm &> /dev/null; then
+        echo "Error: helm is not installed. Please install it to proceed." >&2
+        exit 1
+    else
+        echo "✓ helm $(helm version --short) found."
+    fi
+
+    # Check if helm 'diff' plugin is installed
+    if ! helm plugin list | grep -q "diff"; then
+        echo "Error: helm 'diff' plugin not found. Installing now..."
+        helm plugin install "https://github.com/databus23/helm-diff"
+        echo "✓ helm diff plugin $(helm diff version) is installed."
+    else
+        echo "✓ helm diff plugin $(helm diff version) found."
+    fi
 
     # Check if 'yq' is installed
     if ! command -v yq &> /dev/null; then
@@ -18,14 +36,8 @@ prep_req () {
         echo "✓ $(yq --version) found."
     fi
 
-    # Check if helm 'diff' plugin is installed
-    if ! helm plugin list | grep -q "diff"; then
-        echo "helm 'diff' plugin not found. Installing now..."
-        helm plugin install "https://github.com/databus23/helm-diff"
-        echo "✓ helm diff plugin $(helm diff version) is installed."
-    else
-        echo "✓ helm diff plugin $(helm diff version) found."
-    fi
+    # new line 
+    echo ""
 }
 
 load_config () {
@@ -67,24 +79,49 @@ load_config () {
             HELM_ARGS+=(--values "$val_file")
         fi
     done < <(yq e '.values[]?' "$helm_conf")
+
+    kube_ctx=$(yq e '.context' "$helm_conf")
+    if [ -n "$kube_ctx" ] && [ "$kube_ctx" != "null" ]; then
+        HELM_ARGS+=(--kube-context "$kube_ctx")
+    fi
 }
 
-install() {
-    echo "Installing package: ${HELM_ARGS[0]}"
-    helm upgrade --install "${HELM_ARGS[@]}" \
-        --create-namespace
+deploy() {
+    read -p "✓ Do you want to deploy '${HELM_ARGS[0]}'? [y/n]: " choice
+    case $choice in
+        y)
+            echo "Deploy: ${HELM_ARGS[0]}"
+            helm upgrade --install "${HELM_ARGS[@]}" \
+                --create-namespace
+            ;;
+        *) echo "✓ Cancelled by user." ;;
+    esac
 }
 
 diff() {
-    echo "Preview changes on package: ${HELM_ARGS[0]}"
-    helm diff upgrade "${HELM_ARGS[@]}" \
-        -C 4 --three-way-merge
+    # Check if the captured variable is NOT an empty string
+    found_release=$(helm list -f "^${HELM_ARGS[0]}$" -q -A --deployed 2>/dev/null)
+
+    if [ -n "$found_release" ]; then
+        # Release found (string is not empty)
+        echo "Preview changes: ${HELM_ARGS[0]}"
+        helm diff upgrade "${HELM_ARGS[@]}" \
+            --context 4 --three-way-merge
+    else
+        echo "Error: '${HELM_ARGS[0]}' not found"
+    fi
 }
 
 uninstall() {
-    echo "Removing package: ${HELM_ARGS[0]}"
-    helm uninstall "${HELM_ARGS[0]}" -n "${HELM_ARGS[5]}"
-#        --cascade foreground
+    read -p "✓ Do you want to uninstall '${HELM_ARGS[0]}'? [y/n]: " choice
+    case $choice in
+        y)
+            echo "Remove: ${HELM_ARGS[0]}"
+            helm uninstall "${HELM_ARGS[0]}" -n "${HELM_ARGS[5]}"
+            #    --cascade foreground
+            ;;
+        *) echo "✓ Cancelled by user." ;;
+    esac
 }
 
 ### Main script logic
@@ -95,32 +132,25 @@ if [[ $# -eq 0 ]]; then
 fi
 
 COMMAND="$1"
-case "$COMMAND" in
+case "${COMMAND}" in
+    deploy)
+        load_config "$@"
+        diff
+        deploy
+        ;;
     diff)
         load_config "$@"
         diff
-        ;;
-    install)
-        load_config "$@"
-        install
         ;;
     uninstall)
         load_config "$@"
         uninstall
         ;;
-    update)
-        load_config "$@"
-        diff
-        read -p "Do you want to apply the changes? [y/n]: " choice
-        case $choice in
-            y) install ;;
-        esac
-        ;;
     help)
         usage
         ;;
     *)
-        echo "Error: Unknown command '$COMMAND'" >&2
+        echo "Error: Unknown command '${COMMAND}'" >&2
         usage
         ;;
 esac
