feat(sh): helm diff plugin install

diff --git a/scripts/helmctl b/scripts/helmctl
--- a/scripts/helmctl
+++ b/scripts/helmctl
@@ -10,17 +10,21 @@ usage() {
 prep_req () {
     local tool_conf=".helmctl.conf"
 
-    # Check if yq is installed
-    if command -v yq &> /dev/null; then
-        if [ ! -f "$tool_conf" ]; then
-            touch "$tool_conf"
-
-            echo "yq found. Continuing with the script..."
-            yq --version
-        fi
-    else
+    # Check if 'yq' is installed
+    if ! command -v yq &> /dev/null; then
         echo "Error: yq is not installed. Please install it to proceed." >&2
         exit 1
+    else
+        echo "✓ $(yq --version) found."
+    fi
+
+    # Check if helm 'diff' plugin is installed
+    if ! helm plugin list | grep -q "diff"; then
+        echo "helm 'diff' plugin not found. Installing now..."
+        helm plugin install "https://github.com/databus23/helm-diff"
+        echo "✓ helm diff plugin $(helm diff version) is installed."
+    else
+        echo "✓ helm diff plugin $(helm diff version) found."
     fi
 }
 
